-- MySQL Script generated by MySQL Workbench
-- Sun May 21 20:52:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema open_data_management_system
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS `open_data_management_system` ;

-- -----------------------------------------------------
-- Schema open_data_management_system
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `open_data_management_system` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `open_data_management_system` ;

-- -----------------------------------------------------
-- Table `open_data_management_system`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`Group` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`Group` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idGroup_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_data_management_system`.`Donate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`Donate` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`Donate` (
  `id` INT NOT NULL,
  `details` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_data_management_system`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`User` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `avatar` BLOB NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `id_group` INT NOT NULL,
  `id_donate` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_User_Group1_idx` (`id_group` ASC) VISIBLE,
  INDEX `fk_User_Donate1_idx` (`id_donate` ASC) VISIBLE,
  CONSTRAINT `fk_User_Group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `open_data_management_system`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Donate1`
    FOREIGN KEY (`id_donate`)
    REFERENCES `open_data_management_system`.`Donate` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_data_management_system`.`Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`Permission` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`Permission` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_data_management_system`.`Data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`Data` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`Data` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `date_create` DATE NOT NULL,
  `id_creator` INT NOT NULL,
  `file_csv` BLOB NOT NULL,
  `id_category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_data_management_system`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`Category` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`Category` (
  `id_data` INT NOT NULL,
  `id_user` INT NOT NULL,
  INDEX `fk_Category_Data1_idx` (`id_data` ASC) VISIBLE,
  INDEX `fk_Category_User1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Category_Data1`
    FOREIGN KEY (`id_data`)
    REFERENCES `open_data_management_system`.`Data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `open_data_management_system`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `open_data_management_system`.`Access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `open_data_management_system`.`Access` ;

CREATE TABLE IF NOT EXISTS `open_data_management_system`.`Access` (
  `id_group` INT NOT NULL,
  `id_permission` INT NOT NULL,
  INDEX `fk_Access_Group1_idx` (`id_group` ASC) VISIBLE,
  INDEX `fk_Access_Permission1_idx` (`id_permission` ASC) VISIBLE,
  CONSTRAINT `fk_Access_Group1`
    FOREIGN KEY (`id_group`)
    REFERENCES `open_data_management_system`.`Group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Access_Permission1`
    FOREIGN KEY (`id_permission`)
    REFERENCES `open_data_management_system`.`Permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
